version: '3.8'
services:
  client-backend:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      service-db:
        condition: service_healthy
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/ads
      - SPRING_DATASOURCE_USERNAME=me
      - SPRING_DATASOURCE_PASSWORD=me
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate

  service-db:
    image: postgres:14.7-alpine
    environment:
      - POSTGRES_PASSWORD=me
      - POSTGRES_USER=me
      - POSTGRES_DB=ads
#      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "--quiet" ]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "15432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data: