version: '3.8'
services:
  ads_backend:
    image: ads_backend
    container_name: ads_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db_postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_postgres/ads
      - SPRING_DATASOURCE_USERNAME=me
      - SPRING_DATASOURCE_PASSWORD=me

  db_postgres:
    image: postgres:14.7-alpine
    container_name: db_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: me
      POSTGRES_USER: me
      POSTGRES_DB: ads